### ISSUE TITLE
Possible connection to WS through terminal

### ISSUE THREAD

**Issue by HekMe** [Cel51/cel51.website.startpage#3]
Hello
is it possible to connect WebSocket through the terminal? if yes can you help me make it real? =)
thanks

**Comment by Cel51** [comment]
Hi,
What kind of things do you want to make with Websockets ? A chat or something like that ?

**Comment by HekMe** [comment]
Chat... or connection to console

**Comment by Cel51** [comment]
Which kind of console ?

**Comment by HekMe** [comment]
Java console for example

**Comment by Cel51** [comment]
I can add a javascript console into the terminal but I don't see the purpose to connect to a java console using websocket

**Comment by Oshayr** [comment]
the option to connect to ssh would be nice
