### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by tenebris0011** [Cel51/cel51.website.startpage#5]
Not so much an issue, as a question.
I can't seem to find where you have the C vs F set.
I have dug through the jquery for the weather, and can't seem to find the right setting.
I am a little new to HTML, CSS, and Jquery. Do you think you could point me to what I need to change to make the weather use F. I already changed the locations.

Awesome startpage btw. First one I have ever seen that looks anything like this.

**Comment by Cel51** [comment]
Simply search **simpleWeather** inside the **script/min/app.js**, you will see after the **unit:"c"** that you need to change into **unit:"F"**

**Comment by tenebris0011** [comment]
Thank you so very much

**Comment by LaconicCode** [comment]
Where do I set my location for the weather? I tried looking in the same place but it doesnt seem to work.

**Comment by tenebris0011** [comment]
You are looking for the section of code like below;
`$.simpleWeather({zipcode:"",woeid:locations[t],location:"",unit:"c"`

**Comment by LaconicCode** [comment]
Thanks! How would I add multiple ones then?
