### ISSUE TITLE
Uncaught TypeError: Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by ssnailed** [Cel51/cel51.website.startpage#6]
Uncaught TypeError: Cannot read property '1' of undefined(anonymous function) @ favorites.js:1m.extend.each @ jquery-1.11.3.min.js:2m.fn.m.each @ jquery-1.11.3.min.js:2(anonymous function) @ favorites.js:1m.extend.each @ jquery-1.11.3.min.js:2m.fn.m.each @ jquery-1.11.3.min.js:2initFavorites @ favorites.js:1init @ app.js:30(anonymous function) @ app.js:570j @ jquery-1.11.3.min.js:2k.fireWith @ jquery-1.11.3.min.js:2m.extend.ready @ jquery-1.11.3.min.js:2J @ jquery-1.11.3.min.js:2
I only know very simple HTML and java, but I was trying to get a homepage running. Love yours btw, but i get this issue when I start up the site. This is all that loads in:
![image](https://cloud.githubusercontent.com/assets/18505093/14585309/60912664-043d-11e6-991f-3b9af75db0aa.png)
This is my repository: https://github.com/xMadHat/startpage

**Comment by Cel51** [comment]
What's inside your var.js ?

**Comment by ssnailed** [comment]
var username = "MadHat"
var clientid = "be212a58528168962a39c64052c1d88e";
var redirecturi = "http://localhost:8002/callback.html";
var locations = [
  "2363527",
  "638806"
];
var images = [
  "1412446496031.jpg"
];
var searchs = [
  ["!g", "https://www.google.ch/#q="],
  ["!y", "https://www.youtube.com/results?search_query="],
  ["!w", "https://en.wikipedia.org/w/index.php?search="]
];
var favorites = [
  [ "Work",
    [
      ["edline" , "https://.edline.net/Index.page", "el"],
      ["google docs" , "https://docs.google.com/document/u/0/", "gdc"],
      ["gmail" , "https://mail.google.com/mail/u/0/#inbox", "gm"],
      ["google drive" , "https://drive.google.com/drive/u/0/my-drive", "gdr"]
    ]
  ],
  [ "Social",
    [
      ["messenger" , "https://.messenger.com/", "fm"],
      ["facebook" , "https://.facebook.com/" , "fb"],
      ["raid" , "https://raidforums.com/", "rf"],
      ["bscotch" , "https://forums.bscotch.net/index.php", "bs"]
    ]
  ],
  [ "Download",
    [
      ["thepiratebay", "http://thepiratebay.se", "tpb"],
      ["T411", "http://.t411.in/", "t411"]
    ]
  ],
  [ "Frequent",
    [
      ["youtube", "https://.youtube.com/", "yt"],
      ["inventory", "https://steamcommunity.com/id/banksy42/invent", "inv"],
      ["netflix", "https://.netflix.com/browse", "nf"],
      ["slither", "https://slither.io/", "sl"],
      ["net config", "http://192.168.9.1/cgi-bin/luci", "nc"]
    ]
  ],
  [ "4chan",
    [
      ["/b/", "http://4chan.org/b/", "b"],
      ["/wg/", "http://4chan.org/wg/", "wg"],
      ["/g/", "http://4chan.org/g/", "g"]
    ]
  ],
  [ "Others",
    [
      ["glitcher", "http://jkirchartz.com/Glitchy3bitdither/GlitchCruiser.html", "gb"]
      ["ifunny", "http://ifunny.com", "if"]
    ]
  ]
];
var feeds = [
  ["cs:go","http://blog.counter-strike.net/index.php/feed/"],
  ["cs:go news", "http://feeds.thescoreesports.com/csgo.rss"],
  ["Listen to this", "https://www.reddit.com/r/listentothis/.rss"]
];

I changed the locations, links, username and image names.

When I open the site, some of the other boxes pop up briefly and then disappear. I looked at your site, and I see that my site does what yours does and then stops when it fails to run the scripts.

Also, I'm not sure what the numbers are for location, do you know how I could find them for my location?

**Comment by Cel51** [comment]
You forgot a comma at the end of the glitcher favorite

`["glitcher", "http://jkirchartz.com/Glitchy3bitdither/GlitchCruiser.html", "gb"]`
Must be
`["glitcher", "http://jkirchartz.com/Glitchy3bitdither/GlitchCruiser.html", "gb"],`

http://simpleweatherjs.com/ try to find here your location code, I don't know how to anymore

**Comment by ssnailed** [comment]
Thanks for taking your time! 
It looks like you used a yahoo WOEID for you location

**Comment by Cel51** [comment]
Oh, yeah, it's that

**Comment by Spemaky10k** [comment]
It also seems to fail with any WOEIDs longer than the 6 digits that yours are.

**Comment by Cel51** [comment]
Which woeid do you use ?

**Comment by Spemaky10k** [comment]
My apologies, 2379574

**Comment by Cel51** [comment]
It works with me

"2379574" is Chicago ?

**Comment by Spemaky10k** [comment]
Indeed, it is.  That's working here now too without having changed my var.js, so I wonder if yahoo weather was having issues and the Sainte Croixe info I left while configuring was cached?

**Comment by Cel51** [comment]
Dunno, tried it like fifty times with Sainte-Croix still in and worked all the time
