### ISSUE TITLE
cpu usage

### ISSUE THREAD

**Issue by ineeee** [Cel51/cel51.website.startpage#7]
website uses 100% cpu while loading, and 50% when its open doing nothing

![](https://comfy.moe/kqitte.png)

also
![](https://comfy.moe/dqgyoz.png)

**Comment by Cel51** [comment]
It's caused by the background animation, simply remove the background.js file in script folder and the link to it in the HTML page.

**Comment by ineeee** [comment]
well, it does fix it ¯\\\_(ツ)_/¯

![](https://comfy.moe/cdpzgh.png)
