### ISSUE TITLE
Which coordinates to use?

### ISSUE THREAD

**Issue by dirsigler** [Cel51/cel51.website.startpage#8]
Unfortunately there is no documentation about how to set up the location settings.
A research to the given numbers 784201, 784302 didn't helped me.

Please provide more information.
Thanks!

**Comment by ghost** [comment]
It is a Yahoo WOEID. http://woeid.rosselliot.co.nz/lookup

I can't for the life of me figure out how to change it to F from C. I break it evertime I try.
